### ISSUE TITLE
Research on using screener to get users to sign up for interviews

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#2996]
Let's find out if we can re-use the screener from 18-F to get users to sign up for user research, and if not, what we need to do to implement on our own. 

Related to #2920

**Comment by brentryanjohnson** [comment]
@laurenancona Hi Lauren! We'd like to have another go at research recruitment, and we're wondering if we can use your tag manager screener again. As I'm sure you recall, we implemented it for a sprint [back in October](https://github.com/ONRR/doi-extractives-data/pull/2413/commits/716b610eda339030732861f1b28789b4fbab2467).

If we can't reuse it, no worries. We just don't want to reinvent the wheel if we don't have to!

**Comment by laurenancona** [comment]
@brentryanjohnson Totally can do. In fact, I can literally switch it back on any time (assuming the GTM snippet is still present)

**Comment by brentryanjohnson** [comment]
Awesome, @laurenancona! We still have the Tag Manager snippet at the end of the `<head>` tag.

Where will the responses go when we flip the switch back on? It would be great if we can direct the responses to @mcharg, our UX designer.

**Comment by mcharg** [comment]
I'm guessing they go to this spreadsheet: https://docs.google.com/spreadsheets/d/1_UGBNzWUpAXHXKAEyR4psts4u2UiaJy0VprVDqEw29s/edit#gid=996687344

**Comment by mcharg** [comment]
Next step: #2920 to implement
