### ISSUE TITLE
Fix missing Explore data clicks in analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4654]
They're missing for September because of a class change.

**Comment by brentryanjohnson** [comment]
This should be fixed now. Let's test tomorrow, @mcharg.

**Comment by mcharg** [comment]
It's still not showing up as an event category on the Explore Data page.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0f82539e-24f3-4b51-a95c-e6298cc9431c)

**Comment by brentryanjohnson** [comment]
They would still aggregate under "Explore data clicks," but yes, it appears they still aren't. I'll look into it again today.

**Comment by brentryanjohnson** [comment]
I'm going to create new tag for `/explore/` and keep and rename the existing one for state page nav. Hopefully that will fix our problem.

**Comment by mcharg** [comment]
@brentryanjohnson This is still broken.  Only 1 explore data click was tracked on the explore page for all of October.

**Comment by jennmalcolm** [comment]
Can't start until Jan 2020 when we should get DAP access back.
